name: Build

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: number
      pnpm-version:
        required: true
        type: string
      build-command:
        required: true
        type: string
        description: Build command to execute (e.g., 'pnpm build' or 'vercel build --prod')
      artifact-name:
        required: false
        type: string
        default: build-output
      artifact-path:
        required: true
        type: string
        description: Path to the build output (e.g., '.next/' or '.vercel/output')
      build-to-vercel:
        required: false
        type: boolean
        default: false
        description: Whether to install Vercel CLI before building
      infisical-project-slug:
        required: true
        type: string
        description: "The Infisical project slug"
      infisical-secret-path:
        required: false
        type: string
        default: "/"
        description: "The path to secrets in Infisical"
    secrets:
      INFISICAL_CLIENT_ID:
        required: true
      INFISICAL_CLIENT_SECRET:
        required: true
      VERCEL_TOKEN:
        required: false
      VERCEL_PROJECT_ID:
        required: false
      VERCEL_ORG_ID:
        required: false

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        if: inputs.build-to-vercel
        run: pnpm install -g vercel@latest

      - name: Pull Secrets from Infisical
        uses: infisical/secrets-action@v1.0.9
        with:
          env-slug: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          project-slug: ${{ inputs.infisical-project-slug }}
          secret-path: ${{ inputs.infisical-secret-path }}

      - name: Build
        run: ${{ inputs.build-command }}

      - name: Archive Build Output
        run: tar -czf ${{ inputs.artifact-name }}.tgz ${{ inputs.artifact-path }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-name }}.tgz
          retention-days: 1
